[package]
name = "nyhetsklipp"
version = "2022.2.2"
edition = "2021"

[dependencies.serde]
version = "1.0.136"
default-features = false

[dependencies.rocket]
version = "0.5.0-rc.1"
default-features = false
features = ["json", "serde_json"]